version: '3.9'

services:
  api-gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: src/api-gateway/Dockerfile
    restart: always
    networks:
      - app-network
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    depends_on:
      - postgres
    command: yarn run start:dev

  catalog:
    container_name: catalog
    build:
      context: .
      dockerfile: src/catalog/Dockerfile
    restart: always
    networks:
      - app-network
    ports:
      - ${CATALOG_PORT}
    depends_on:
      - postgres
    command: yarn run start:dev

  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    networks:
      - app-network
    ports:
      - "${DB_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env

networks:
  app-network:
    driver: bridge

volumes:
  app-volume:


